### ISSUE TITLE
Example doesn't run correctly

### ISSUE THREAD

**Issue by GarthDB** [remijs/remi#11]
I was running into an issue with registering a plugin so I went back to the examples in the repo and ran into the same issue.

I'm running it on node v4.2.2

```sh
❯ node index.js
[TypeError: Cannot read property 'attributes' of undefined]
```

**Comment by zkochan** [comment]
Hi, sorry, I did some breaking changes in v2 and did not update the example/documentation.

I've rewritten it to TypeScript and simplified the API to have simpler types.

**Comment by GarthDB** [comment]
Thanks @zkochan!
